Fix the unexplicable bug
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e4b3c8e719f2> in <module>()
     93
     94 print('\n All before:')
---> 95 for message in bob.messages.list_all_before(all_messages[0].id):
     96     print(message.name, message.text)

~/code/apps/Groupy/groupy/api/messages.py in list_all_before(self, message_id, **kwargs)
    216         :rtype: :class:`~groupy.pagers.MessageList`
    217         """
--> 218         return self.list_before(message_id=message_id, **kwargs).autopage()
    219
    220     def create(self, text=None, attachments=None, source_guid=None):

TypeError: list_before() missing 1 required positional argument: 'message_id'

    def list_all_before(self, message_id, **kwargs):
        """Return all direct messages created before a message.

        This can be used to page backwards through messages.

        :param str message_id: the ID of a message
        :return: direct messages
        :rtype: :class:`~groupy.pagers.MessageList`
        """
        return self.list_before(message_id=message_id, **kwargs).autopage()

    def list_before(self, message_id, **kwargs):
        """Return a page of direct messages created before a message.

        This can be used to page backwards through messages.

        :param str message_id: the ID of a message
        :return: direct messages
        :rtype: :class:`~groupy.pagers.MessageList`
        """
        return self.list(before_id=message_id, **kwargs)

wtf?